---
title: "The Tadpole Olympics"
description: |
  For my B.S. thesis project at Yale, I measured how fast wood frog tadpoles swim in response to a simulated predator attack, and how that swimming speed relates to their developmental rate. It turns out that developing fast comes with a performance cost, and that tradeoff might help to explain some of the patterns we've observed in wood frogs' developmental rates in the past.
  A short description of the post.
author:
  - name: Kaija Gahm
    url: {}
date: 01-29-2021
output:
  distill::distill_article:
    self_contained: false
preview: tadpole.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Introduction
For my senior (B.S.) thesis in E&EB at Yale, I studied a tradeoff between growth rate and swimming performance in wood frog tadpoles.

What does that mean? Basically, my collaborator [Andis](https://www.azandisresearch.com/) and I raised tadpoles in the lab under warm and cold conditions. Since frogs are cold-blooded, the warm tadpoles grew faster than the cold tadpoles. 

On the one hand, growing rapidly is good for animals like wood frogs, who need to escape from predators and compete for mating opportunities. But when we stuck our tadpoles into an arena and tested how fast they swam, we found that the tadpoles pay a cost for that fast growth. The fast-growing (warm) tadpoles didn't perform as well in their swimming trials as the slow-growing (cold) tadpoles. 

This kind of tradeoff exists in other animals too, but we tested several populations of tadpoles and found that the effect was really consistent, no matter which population the tadpoles came from. 

### What determines how fast a tadpole grows?
Why is this important? Well, our findings might help to explain a pattern that my lab has been wondering about for a while, called "countergradient variation". Here's how it works. 
We know that growing fast is helpful to tadpoles for a lot of reasons: they might have better mating or survival success as adults (though we don't know this for sure); they might get too big for aquatic predators to eat while they're still tadpoles; they can be sure to leave their ephemeral ponds before the water dries up in the summer; and they can get a head start on terrestrial life, perhaps outcompeting slower-growing tadpoles.

Two factors can help frogs grow fast: 1) environmental factors, like the temperature of the water they live in, and 2) genetic factors: that is, their genes can predispose them to "intrinsically" fast growth, independent of their environment.

Let's say we have two ponds in an imaginary forest, called "Fire Pond" and "Ice Pond" because one has really warm water and the other has really cold water. 

#### Environmental factors
We know that the tadpoles living in Fire Pond will grow faster than the tadpoles living in Ice Pond, since frogs are cold-blooded and their growth is pretty heavily influenced by the temperature of the water around them. Warmer water -> faster growth! This is the relationship that we made use of to manipulate our frogs' developmental rates in the lab.

#### Genetic factors
Fire Pond and Ice Pond are pretty far apart, and wood frogs tend to return to the same ponds where they grew up to breed. So, the frog populations in Fire and Ice can evolve roughly independently of each other.

So, if fast growth is unequivocally beneficial, then we might expect that both the Fire and Ice populations would evolve toward faster intrinsic growth and development. Put another way: natural selection would favor tadpoles that had genes for fast growth over those who grew more slowly, independent of the surrounding water temperature. We would expect to see this evolutionary trend in *both* ponds. Tadpoles from both Fire and Ice would evolve fast intrinsic growth rates, such that the Ice tadpoles will grow *fast* despite the cold water, and the Fire tadpoles will grow *EXTRA FAST* from the combined effects of genetics and warm water.

But this pattern is not what researchers, including the Skelly lab, have observed! When other studies have taken tadpoles from Fire and Ice and reared them at the same temperature (so, removing the effects of the different pond temperatures), they find that tadpoles from Fire grow more slowly than tadpoles from Ice. So, for some reason, those Fire frogs aren't evolving to grow super fast intrinsically, even though doing so would let them have an edge over the chilly little Ice frogs.

### Putting it together
The pattern that I've described above is called "countergradient variation" because the frogs' intrinsic (genetic) growth rates run in the opposite direction (*counter*-gradient) as their environmental circumstances.

For a while, we've wondered why we see this pattern. Why don't the Fire tadpoles make the most of what seems like an advantage: their warm water? The countergradient pattern suggests that there must be a tradeoff, something that makes growing *EXTRA FAST* not quite so advantageous after all.

That's where my study comes in. It turns out, growing fast comes with a cost in burst swimming speed! If you're a tadpole, you might get bigger faster, but if you also swim more slowly than your slower-growing peers, you're at risk of getting gobbled up by a predator. If that happens, all that growing would be for nothing.

### Paper
My collaborators and I published this work, and if you want to read more, you can `r xfun::embed_file(text = "download the paper", 'Gahm_etal_2020.pdf')`. But I hope my description is a little easier to get through than the paper itself.

If you want a more detailed summary of the paper, with reference to each of its figures, Andis did a great job explaining it in [his blog post](https://www.azandisresearch.com/2020/12/24/hot-competition-and-tadpole-olympics/).

### Talk
If you want to learn more about my work and would prefer to see a video of a talk I gave, aimed at a more general audience than the published paper, you can watch it below. This talk was given as part of the 2020 end-of-year E&EB Senior Symposium, which I organized as a remote event due to the COVID-19 pandemic.

<iframe width="720" height="480" src="tadpoleOlympics.mp4" align="middle" frameborder="0" allowfullscreen></iframe>

### Acknowledgements and reflections
This work was made possible with the tremendous support of the [Skelly Lab](https://campuspress.yale.edu/skellylab/) in the [Yale School of the Environment](https://environment.yale.edu/). Andis Arietta, in particular, was a great mentor and collaborator. You should check out his research on [his website](https://www.azandisresearch.com/) and [follow him](https://twitter.com/azandisarietta) on Twitter.

Thanks to Kirby Broderick and Simon Stump for help with the MATLAB code I wrote to analyze all my tadpole videos. Thanks to Joaquin Bellomio for help ground-truthing videos, and to Adriana Rubinstein and David Skelly for assistance in the lab.

Finally, I want to recognize the privilege that allowed me to publish my research in 2020. Apart from summer fellowships, Yale doesn't pay undergrads for research hours beyond course credit. I was able to spend a lot of extra hours in the lab during my senior year, hours that were not an option for a lot of my fellow students because they had to prioritize fulfilling their student income contributions (SIC) or working to support their families. Yale needs to abolish the SIC ([SUN at Yale](https://sunatyale.org/) is doing great work toward this end) and pay undergraduate researchers to help even out these opportunities.

When the COVID-19 pandemic hit, I was able to return to a calm and supportive home environment, where I had lots of time to work on preparing this manuscript for publication. Many of my friends had their thesis work cut short, and they had far more pressing things on their minds than writing and publishing papers. Across the scientific community, some academics are publishing more under lockdowns, while others (disproportionately women, people of color, those caring for children, etc.--aka people who were already at a disadvantage before this pandemic made things worse) have less time, not more, to devote to their work (see [this](https://www.insidehighered.com/news/2020/04/21/early-journal-submission-data-suggest-covid-19-tanking-womens-research-productivity) and [this](https://www.nature.com/articles/d41586-020-01294-9), although [this](https://github.com/drfreder/pandemic-pub-bias/blob/master/README.md) calls things into question. I don't have good data for disparities by race and family status, and if/when I find papers that support/refute my intuition above, I'll change my view accordingly!). 

I hope that in the coming years, we will see academia recognize that traditional metrics of success, like publication numbers and grant awards, are far from equitable, especially in the wake of this troubled year.

Thank you for reading, and if you have any questions about my work, please feel free to reach out!
